#import "wdf.typ": *

#show: template.with(
  title: [Variational Inference: Modeling and Approximate Inference],
  title-short: [Variational Inference],
  authors: "CSC 5666: Advanced Machine Learning, Fall 2026",
  authors-short: [CSC 5666],
  title-extra: [Professor Austin P. Wright: Course Notes],
  date: none,
  toc: false,
  full: false,
  header-content: none,
  abstract: [A model-first introduction to variational inference. Starting from a Bayesian Gaussian mixture, these notes develop the ELBO, mean-field coordinate ascent, inference versus learning, and the transfer to amortized neural inference. The emphasis is on choosing and evaluating an inference design, not only deriving an optimizer.],
  bib: none,
  serif: true,
  exam: false,
)

#let checkpoint(body) = discussion(vspace: 0em)[#body]

= The Modeling Problem
#text(
  size: 8pt,
  fill: luma(45%),
  style: "italic",
)[Primary sources: Murphy (2023), Chapter 10; Ganguly and Earp (2021), _An Introduction to Variational Inference_.]

A latent-variable model describes observations $x$ using unobserved variables $z$:
$
  p_theta (x, z)=p_theta (z)p_theta (x|z).
$ <joint-model>
The model runs _forward_: sample a latent explanation from the prior, then generate an observation from the likelihood. Inference reasons in the opposite direction. After observing $x$, we want
$
  p_theta (z|x)=(p_theta (x, z))/(p_theta (x)),
  quad p_theta (x)=integral p_theta (x, z)dif z.
$ <posterior>
The joint is often easy to evaluate at one configuration even when the evidence requires summing or integrating over an enormous set. Exact inference exploits special graph structure but becomes impractical in dense or high-dimensional models. MCMC approximates expectations with posterior samples and can represent complicated posteriors, but may be expensive. _Variational inference_ (VI) turns inference into optimization: choose a tractable family $cal(Q)$ and find a member near the posterior.

#def(
  term: "Variational inference",
)[For a fixed generative model, choose an approximate posterior $q in cal(Q)$ and optimize it to be close to $p_theta (z|x)$. The result depends separately on the model, the family, and the optimization procedure.]

== Running model: a Bayesian Gaussian mixture

Let $x_(1:N)$ be scalar observations generated by one of $K$ components. We use global latent component means $mu_(1:K)$ and one local latent assignment $c_i$ per observation:
$
          mu_k & ∼ cal(N)(0,tau^2), quad k=1,dots,K, \
           c_i & ∼ "Cat"(1/K,dots,1/K), \
  x_i|c_i=k,mu & ∼ cal(N)(mu_k,1).
$ <mixture-model>
The joint is
$
  p(x,mu,c)=product_(k=1)^K p(mu_k)
  product_(i=1)^N p(c_i)p(x_i|c_i,mu).
$ <mixture-joint>
The means are _global_: every observation informs them. Assignments are _local_: $c_i$ belongs to observation $i$. Even with fixed hyperparameters, exact posterior inference must reason over $K^N$ assignment configurations while coupling assignments to uncertain means.

#checkpoint[
  In @mixture-model identify the observations, local unknowns, global unknowns, priors, and likelihood. Then describe one posterior question a point estimate cannot answer, one data pattern the equal weights/unit variances may fit poorly, and a posterior predictive check that could reveal it.
]

= Choosing an Approximation

Standard VI minimizes reverse KL:
$
  q^*=limits("argmin")_(q in cal(Q))D_("KL")(q(z)||p_theta (z|x)).
$ <vi-objective>
We state reverse KL first as the design target; the next section derives the computable ELBO used to optimize it. The expectation is under tractable $q$. Forward KL would average under the unavailable posterior and is generally not a computable objective here.

Reverse KL strongly penalizes placing $q$-mass where the posterior density is tiny. For separated modes, it may select one mode rather than cover all explanations. With a diagonal Gaussian approximation to a correlated Gaussian posterior, it cannot represent correlation and is often too narrow. These are tendencies, not universal laws; behavior depends on the target and family.

== Mean field for the mixture

A mean-field family factorizes selected groups:
$
  q(mu,c)=product_(k=1)^K q_k (mu_k)
  product_(i=1)^N q_i (c_i),
$ <mixture-mean-field>
with
$
  q_k (mu_k)=cal(N)(mu_k|m_k,s_k^2),
  quad q_i (c_i)="Cat"(c_i|r_i).
$
Here $r_(i k)=q_i (c_i=k)$ is a soft responsibility. The variational parameters $(m,s^2,r)$ are fitted _after seeing the data_, even though $x$ is suppressed from the notation. Mean field does not claim that the true posterior factorizes. In fact, mixture assignments and component means are posterior-dependent: changing belief about one changes the other.

Three errors must remain distinct:

- *Model error:* $p_theta (x, z)$ does not describe the data-generating structure we need.
- *Approximation error:* $cal(Q)$ excludes posterior dependence, skewness, or modes that matter.
- *Optimization error:* the algorithm fails to find the best available $q in cal(Q)$.

A richer family can reduce approximation error but may be harder to optimize. A better optimizer cannot recover dependence excluded by the family.

#checkpoint[
  In @mixture-mean-field, which dependencies are removed? Would making every factor neural or highly expressive restore dependence _between_ factors? Explain.
]

= The Evidence Lower Bound

Assume the displayed expectations are finite and $q$ has no mass outside the posterior support. Expand reverse KL using Bayes' rule:
$
  D_("KL")(q(z)||p_theta (z|x))
  &=EE_(q)[log q(z)-log p_theta (z|x)]\
  &=EE_(q)[log q(z)-log p_theta (x, z)]+log p_theta (x).
$
Define the _evidence lower bound_ (ELBO)
$
  cal(L)(theta,q;x)
  eq.def EE_(q)[log p_theta (x, z)-log q(z)].
$ <elbo>
Then
$
  underbrace(log p_theta (x), "log evidence")
  =underbrace(cal(L)(theta,q;x), "ELBO")
  +underbrace(D_("KL")(q(z)||p_theta (z|x)), "inference gap").
$ <elbo-identity>
Because KL is nonnegative, $cal(L)<=log p_theta (x)$. For fixed $theta$, maximizing the ELBO over $q$ is equivalent to minimizing reverse KL. Equality holds exactly when the posterior belongs to the family and is attained.

Two equivalent forms explain what is optimized:
$
  cal(L) & =EE_(q)[log p_theta (x, z)]+H(q), \
         & =EE_(q)[log p_theta (x|z)]-D_("KL")(q(z)||p_theta (z)).
$ <elbo-forms>
The first balances high joint density with variational entropy. The second is expected data fit minus departure from the prior. It is not two unrelated losses.

#colorbox(
  title: "What a larger ELBO does—and does not—show",
  color: red.darken(10%),
)[
  For a fixed model and family, a larger ELBO means a smaller reverse-KL gap. It does not by itself show calibrated uncertainty, useful latent variables, a correct generative model, or larger evidence than a different model whose variational gap is different.
]

#checkpoint[
  Derive @elbo-identity from the KL definition. Why can we optimize $q$ without evaluating $p_theta (x)$? If $theta$ is also updated, which fixed-$theta$ equivalence stops applying even though the ELBO remains computable?
]

= Mean-Field Coordinate Ascent

Hold all factors except $q_j$ fixed. Let $q_(-j)=product_(ell != j)q_ell$. Terms involving $q_j$ can be written
$
  cal(L)(q_j)
  =-D_("KL")(q_j (z_j)||tilde(p)_j (z_j))+"constant",
$
where
$
  tilde(p)_j (z_j) prop exp(EE_(q_(-j))[log p_theta (x, z)]).
$
Thus the free-form coordinate optimum is
$
  q_j^* (z_j) prop exp(EE_(q_(-j))[log p_theta (x, z)]).
$ <cavi>
Read @cavi as: _take the expected log joint, exponentiate, normalize_. It is not the expectation of the joint and is not generally obtained by plugging in means. Only log-joint factors that touch $z_j$ survive, connecting CAVI directly to Markov blankets.

An exact sequential coordinate update cannot decrease the ELBO. The complete mean-field objective may still be nonconvex, so initialization can matter and convergence is not a global-optimum certificate.

== Assignment update in the mixture

For assignment $c_i$, keep only its likelihood term. Under $q_k (mu_k)$,
$
  EE[(x_i-mu_k)^2]=(x_i-m_k)^2+s_k^2.
$
Therefore
$
  log r_(i k)
  ="constant"+x_i m_k-1/2(m_k^2+s_k^2),
$ <responsibility-update>
so normalize over components:
$
  r_(i k) prop exp(x_i m_k-1/2(m_k^2+s_k^2)).
$
The update rewards components whose inferred means fit $x_i$, but penalizes uncertain components through $s_k^2$. Replacing $EE[mu_k^2]$ by $m_k^2$ would erase that uncertainty.

== Component-mean update

Collect the Gaussian prior and all likelihood terms weighted by responsibilities. Completing the square gives
$
  s_k^2 & =(tau^(-2)+sum_i r_(i k))^(-1), \
    m_k & =s_k^2 sum_i r_(i k)x_i.
$ <mean-update>
The effective count $sum_i r_(i k)$ increases posterior precision. The posterior mean is a responsibility-weighted data sum shrunk toward the prior mean zero.

#colorbox(title: "CAVI for the Bayesian mixture", color: blue.darken(10%))[
  + Initialize $(m,s^2,r)$, preferably more than once.
  + Update every responsibility vector $r_i$ with @responsibility-update and normalize.
  + Update every component factor $(m_k,s_k^2)$ with @mean-update.
  + Compute the ELBO and stop when its improvement is small.

  Label symmetry gives equivalent solutions with permuted component names. Poor initialization can also produce inferior local optima.
]

#checkpoint[
  A point lies near component 1, but $q(mu_1)$ is highly uncertain. Explain why @responsibility-update may still prefer a slightly farther but certain component. What modeling behavior would be lost by replacing every $s_k^2$ with zero?
]

= Inference, Learning, and Scale

The phrase “optimize the ELBO” hides two different tasks.

- *Posterior inference:* hold model parameters $theta$ fixed and optimize $q$. The evidence is constant in $q$.
- *Model learning:* optimize $theta$ as well. The evidence changes with $theta$.
- *Variational EM:* alternate an approximate E-step, maximizing $cal(L)$ over $q$, and an M-step, maximizing it over $theta$.
- *Variational Bayes:* place priors on model parameters and include their posterior approximation inside $q$; the mixture above treats $mu$ this way.

These distinctions matter when interpreting the mixture. Updating $q(mu_k)$ represents uncertainty about a Bayesian parameter. Updating a point parameter $theta$ changes the generative model. Both may use the same ELBO, but they answer different questions.

== Minibatches and global/local structure

For a global latent $beta$, local latents $z_n$, and product family $q(beta)product_n q_n (z_n)$, write the ELBO as a global term $G$ plus local terms $ell_n$. A uniformly sampled minibatch $cal(B)$ of size $B$ gives
$
  hat(cal(L))=G+N/B sum_(n in cal(B))ell_n.
$ <minibatch>
Scale the sampled local sum, not the single global prior or entropy term. This rule follows from the global/local modeling decomposition, not from a generic instruction to multiply every minibatch loss by $N/B$.

#checkpoint[
  For the mixture, classify $(mu_k)$ and $(c_i)$ as global or local. Which updates can be computed from one datapoint? Which quantities must aggregate information across the dataset?
]

= Transfer to Neural Latent-Variable Models

A VAE uses the same modeling and inference objects:
$
  p(z)p_theta (x|z),
  quad q_phi (z|x).
$ <vae-model>
The decoder $p_theta (x|z)$ is the generative model. The encoder $q_phi (z|x)$ is an _amortized inference procedure_: instead of optimizing separate variational parameters for every observation, a shared network predicts them. Training jointly learns a model and an inference mechanism.

For a diagonal Gaussian encoder,
$
  q_phi (z|x)=cal(N)(z|mu_phi (x),"diag"(sigma_phi (x)^2)),
$
reparameterize
$
  epsilon∼cal(N)(0,I),
  quad z=mu_phi (x)+sigma_phi (x)dot.o epsilon.
$ <reparam>
The base noise is independent of $phi$, exposing a differentiable path through the sample. A one-sample objective is
$
  hat(cal(L))=log p_theta (x|z)-D_("KL")(q_phi (z|x)||p(z)).
$
For the standard VAE prior $p(z)=cal(N)(0,I)$, the KL is analytic:
$
  D_("KL")=1/2 sum_j (mu_j^2+sigma_j^2-1-log sigma_j^2).
$

== Reconstruction is not generation

A reconstruction samples $z$ from $q_phi (z|x)$ and decodes it. Generation samples $z$ from the prior $p(z)$ and then samples from $p_theta (x|z)$. The encoder is not needed to generate from the learned model. Good reconstruction alone does not establish good density modeling, calibrated inference, or useful latent structure.

Local VI optimizes each case separately. Amortized VI is fast at deployment but may miss the best member of its family. Semi-amortized VI initializes from the encoder and refines locally. Amortization changes _how_ a family member is selected; it does not repair dependence that the family cannot represent. Hard discrete samples generally need exact summation, another gradient estimator, or a relaxation rather than this ordinary Gaussian pathwise construction.

#checkpoint[
  For @vae-model identify $theta$, $phi$, the distribution used for reconstruction, and the distributions used for unconditional generation. Which intervention targets a restrictive diagonal family, and which targets an inaccurate encoder output within that same family?
]

= Limits, Validation, and Method Choice

VI produces an optimized approximation, not a correctness certificate.

- *Family mismatch:* mean field misses dependence; simple families miss skewness or multiple explanations.
- *Reverse-KL underdispersion:* credible intervals and uncertainty-aware decisions may be overconfident.
- *Optimization instability:* different initializations may support different claims about latent structure.
- *Posterior collapse:* in expressive neural models, $q_phi (z|x)approx p(z)$ can indicate that the decoder ignores the latent variable.
- *Model misspecification:* better inference cannot repair a poor likelihood or latent structure.
- *Implementation failure:* wrong KL signs, variance parameterizations, or minibatch scaling can yield plausible-looking output.

Useful checks include exact inference on a tiny instance, multiple starts, analytic gradient checks, comparison with a richer family, inspection of ELBO components, posterior predictive checks, and latent interventions.

== VI or MCMC?

VI is attractive when inference must scale to large datasets, be repeated for many cases, or run quickly after deployment. MCMC is often preferable when faithful posterior dependence and multimodality are central and the model is small enough to support careful sampling. Neither method provides an automatic finite-computation guarantee. They make different approximations and require different diagnostics.

#colorbox(title: "Modeling checklist", color: green.darken(20%))[
  Given a new model, ask:
  + What are the observations, local unknowns, global unknowns, priors, and likelihoods?
  + Which posterior queries matter for the downstream task?
  + What dependence or modes might the proposed $cal(Q)$ remove?
  + Does structure support CAVI, enumeration, or a pathwise gradient?
  + Is inference local, amortized, or refined after amortization?
  + Which checks distinguish model, approximation, optimization, and implementation failures?
]

The core required material ends here. Richer structured families, score-function estimators, normalizing flows, IWAE, detailed damping methods, wake–sleep, expectation propagation, and GAN hybrids are useful extensions but are not prerequisites for the accompanying exam-ready questions.

#text(
  size: 8.5pt,
  fill: luma(35%),
  style: "italic",
)[Ganguly, A., and Earp, S. W. F. (2021). _An Introduction to Variational Inference_, arXiv:2108.13083v3. The article supplies the model-first prototype and mixture example; equations and claims here are independently checked against Murphy (2023) and standard VI identities.]
